name: Issues

on:
  issues:
    types: [opened, closed, reopened]

jobs:
  issue-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue details
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
